Repository risc0/risc0, pull requests merged in 2024-06, with the labels that each got.

#1886 [Docs] Update Getting Started and Installation instructions with `rzup`
  README.md
  rzup/README.md
  website/api/zkvm/install.md
  website/api/zkvm/quickstart.md
Labels: documentation

#1980 Update Docusaurus to 3.4.0 to fix relative `.md` handling
  website/docs/proof-system/proof-system-sequence-diagram.md
  website/docs/proof-system/stark-by-hand.md
  website/docs/proof-system/what-is-a-trace.md
  website/docs/reference-docs/about-arithmetic-circuits.md
  website/docs/reference-docs/about-rs-codes.md
  website/docs/reference-docs/about-starks.md
  website/package.json
  website/sidebars.js
  website/yarn.lock
Labels: documentation, dependencies

#1972 Use lychee to fix broken links
  .github/workflows/website.yml
  website/.gitignore
  website/api/blockchain-integration/eth-examples.md
  website/api/generating-proofs/proving-options.md
  website/api/security-model.md
  website/api/zkvm/guest-code-101.md
  website/api/zkvm/optimization.md
  website/api/zkvm/quickstart.md
  website/api/zkvm/tutorials/overview.md
  website/api/zkvm/zkvm_overview.md
  website/api_versioned_docs/version-0.18/bonsai/bonsai-overview.md
  website/api_versioned_docs/version-0.18/zkvm/developer-guide/guest-code-101.md
  website/api_versioned_docs/version-0.18/zkvm/developer-guide/host-code-101.md
  website/api_versioned_docs/version-0.18/zkvm/developer-guide/receipts.md
  website/api_versioned_docs/version-0.18/zkvm/zkvm_overview.md
  website/api_versioned_docs/version-0.19/bonsai/rest-api.md
  website/api_versioned_docs/version-0.19/zkvm/developer-guide/guest-code-101.md
  website/api_versioned_docs/version-0.19/zkvm/developer-guide/host-code-101.md
  website/api_versioned_docs/version-0.19/zkvm/developer-guide/receipts.md
  website/api_versioned_docs/version-0.19/zkvm/quickstart.md
  website/api_versioned_docs/version-0.19/zkvm/tutorials/hello-world.md
  website/api_versioned_docs/version-0.19/zkvm/tutorials/overview.md
  website/api_versioned_docs/version-0.19/zkvm/zkvm_overview.md
  website/api_versioned_docs/version-0.20/bonsai/rest-api.md
  website/api_versioned_docs/version-0.20/zkvm/optimization.md
  website/api_versioned_docs/version-0.20/zkvm/quickstart.md
  website/api_versioned_docs/version-0.20/zkvm/tutorials/overview.md
  website/api_versioned_docs/version-0.21/blockchain-integration/eth-examples.md
  website/api_versioned_docs/version-0.21/generating-proofs/proving-options.md
  website/api_versioned_docs/version-0.21/security-model.md
  website/api_versioned_docs/version-0.21/zkvm/optimization.md
  website/api_versioned_docs/version-0.21/zkvm/quickstart.md
  website/api_versioned_docs/version-0.21/zkvm/tutorials/overview.md
  website/api_versioned_docs/version-0.21/zkvm/zkvm_overview.md
  website/api_versioned_docs/version-1.0/blockchain-integration/eth-examples.md
  website/api_versioned_docs/version-1.0/generating-proofs/proving-options.md
  website/api_versioned_docs/version-1.0/security-model.md
  website/api_versioned_docs/version-1.0/zkvm/guest-code-101.md
  website/api_versioned_docs/version-1.0/zkvm/optimization.md
  website/api_versioned_docs/version-1.0/zkvm/quickstart.md
  website/api_versioned_docs/version-1.0/zkvm/tutorials/io.md
  website/api_versioned_docs/version-1.0/zkvm/tutorials/overview.md
  website/api_versioned_docs/version-1.0/zkvm/zkvm_overview.md
  website/docs/contributors-guide.md
  website/docs/education.md
  website/docs/proof-system/proof-system-sequence-diagram.md
  website/docs/proof-system/proof-system.md
  website/docs/proof-system/stark-by-hand.md
  website/docs/proof-system/what-is-a-trace.md
  website/docs/reference-docs/about-arithmetic-circuits.md
  website/docs/reference-docs/about-finite-fields.md
  website/docs/reference-docs/about-fri.md
  website/docs/reference-docs/about-plonk.md
  website/docs/reference-docs/about-rs-codes.md
  website/docs/reference-docs/about-starks.md
  website/lychee.toml
  website/package.json
  website/sidebars.js
  website/yarn.lock
Labels: documentation, enhancement

#1966 add info about prove_with_opts and different receipt types
  website/api/generating-proofs/proving-options.md
  website/api_versioned_docs/version-1.0/generating-proofs/proving-options.md
Labels: documentation

#1989 Add Checks to Upload New `bench_pr.yml` Benchmarks or Re-Baseline Current Benchmarks
  .github/workflows/bench_pr.yml
Labels: ci

#1998 Remove `configure-aws-creds` OIDC Step for External PRs
  .github/workflows/bench_pr.yml
Labels: ci

#1906 Nightly Crates Validation Fix
  .github/workflows/nightly.yml
  tools/crates-validator/src/lib.rs
Labels: ci

#1959 Adding doc & diagram for end-to-end recursive proving
  website/api/recursion.md
  website/api_versioned_docs/version-1.0/recursion.md
  website/api_versioned_sidebars/version-1.0-sidebars.json
  website/sidebarsApi.js
Labels: documentation

#1960 adding doc and diagrams for composition
  website/api/recursion.md
  website/api/zkvm/composition.md
  website/sidebarsApi.js
  website/static/diagrams/composition-add-assumption.png
  website/static/diagrams/composition-no-assumptions.png
  website/static/diagrams/composition-resolve.png
Labels: documentation

#2022 Add `crates-validation` Job to Check 10 Crates to Main Workflow
  .github/workflows/main.yml
  tools/crates-validator/README.md
Labels: ci
