Repository risc0/risc0, pull requests merged in 2024-03, with the labels that each got.

#1423 Add documentation for the Verifier contract
  .vscode/ltex.dictionary.en-US.txt
  .vscode/ltex.hiddenFalsePositives.en-US.txt
  .vscode/settings.json
  website/api/blockchain-integration/bonsai-on-eth.md
  website/api/blockchain-integration/contracts/verifier.md
  website/api/blockchain-integration/eth-examples.md
  website/api/bonsai/rest-api.md
  website/api/generating-proofs/remote-proving.md
  website/api/introduction.md
  website/docs/terminology.md
  website/docusaurus.config.js
  website/sidebarsApi.js
Labels: documentation

#1510 Add DevOps Alerting if Nightly Tasks Fail
  .github/workflows/nightly.yml
Labels: ci

#1501 add template for reporting documentation issue
  .github/ISSUE_TEMPLATE/documentation_issue.md
Labels: documentation

#1505 changing `resources` to `education hub`
  website/docs/education.md
  website/docusaurus.config.js
  website/sidebars.js
Labels: documentation

#1574 link updates for verifier contract
  website/api/blockchain-integration/contracts/verifier.md
Labels: documentation

#1491 CI Benchmarks Checks
  .github/actions/sccache/action.yml
  .github/workflows/bench_pr.yml
  .github/workflows/bench_pr_comment.yml
  Cargo.lock
  risc0/zkvm/Cargo.toml
  risc0/zkvm/benches/divan.rs
  risc0/zkvm/benches/fib.rs
Labels: ci

#1571 Update recursion circuit
  compact_proof/docker/ceremony.Dockerfile
  compact_proof/docker/prover.Dockerfile
  compact_proof/groth16/risc0.circom
  compact_proof/groth16/stark_verify.circom
  risc0/circuit/recursion-sys/cxx/poly_fp.cpp
  risc0/circuit/recursion-sys/cxx/step_compute_accum.cpp
  risc0/circuit/recursion-sys/cxx/step_exec.cpp
  risc0/circuit/recursion-sys/cxx/step_verify_accum.cpp
  risc0/circuit/recursion-sys/cxx/step_verify_mem.cpp
  risc0/circuit/recursion-sys/kernels/cuda/eval_check.cu
  risc0/circuit/recursion-sys/kernels/metal/eval_check.metal
  risc0/circuit/recursion/build.rs
  risc0/circuit/recursion/src/control_id.rs
  risc0/circuit/recursion/src/info.rs
  risc0/circuit/recursion/src/layout.rs.inc
  risc0/circuit/recursion/src/poly_ext.rs
  risc0/circuit/recursion/src/recursion_zkr.zip
  risc0/circuit/recursion/src/taps.rs
  risc0/circuit/rv32im-sys/cxx/poly_fp.cpp
  risc0/circuit/rv32im-sys/cxx/step_compute_accum.cpp
  risc0/circuit/rv32im-sys/cxx/step_exec.cpp
  risc0/circuit/rv32im-sys/cxx/step_verify_accum.cpp
  risc0/circuit/rv32im-sys/cxx/step_verify_bytes.cpp
  risc0/circuit/rv32im-sys/cxx/step_verify_mem.cpp
  risc0/circuit/rv32im-sys/kernels/cuda/eval_check.cu
  risc0/circuit/rv32im-sys/kernels/metal/eval_check.metal
  risc0/circuit/rv32im/src/poly_ext.rs
  risc0/groth16/src/docker.rs
  risc0/groth16/src/lib.rs
  risc0/groth16/src/seal_format.rs
  risc0/groth16/src/verifier.rs
  risc0/sys/kernels/zkp/cuda/poseidon2.cu
  risc0/sys/kernels/zkp/metal/poseidon2.metal
  risc0/zkp/src/core/hash/poseidon2/mod.rs
  risc0/zkvm/src/host/receipt.rs
  risc0/zkvm/src/host/recursion/prove/mod.rs
  risc0/zkvm/src/host/recursion/prove/preflight.rs
  xtask/src/bootstrap.rs
  xtask/src/bootstrap_groth16.rs
  xtask/src/templates/control_id_zkr.rs
Labels: Mainnet-Verifier
